from ..models.schemas import CodeAnalysisResponse

class MarkdownGenerator:
    def generate(self, analysis: CodeAnalysisResponse, filename: str, code: str) -> str:
        md = []
        
        md.append(f"# Code Analysis: {filename}\n")
        md.append(f"*Generated by Python Code Explainer*\n")
        md.append("---\n")
        
        md.append("## Table of Contents\n")
        md.append("1. [Overview](#overview)")
        md.append("2. [Variables](#variables)")
        md.append("3. [Functions](#functions)")
        md.append("4. [Classes](#classes)")
        md.append("5. [Imports](#imports)")
        md.append("6. [Diagrams](#diagrams)")
        md.append("7. [Errors and Warnings](#errors-and-warnings)\n")
        md.append("---\n")
        
        md.append("## Overview\n")
        md.append(analysis.overview)
        md.append("\n---\n")
        
        md.append("## Variables\n")
        if analysis.variables:
            for var in analysis.variables:
                md.append(f"### `{var.name}`")
                md.append(f"- **Type**: {var.type}")
                md.append(f"- **Scope**: {var.scope}")
                md.append(f"- **Line**: {var.line_number}\n")
        else:
            md.append("*No significant variables found.*\n")
        md.append("---\n")
        
        md.append("## Functions\n")
        if analysis.functions:
            for func in analysis.functions:
                md.append(f"### `{func.name}({', '.join(func.parameters)})`")
                if func.return_type:
                    md.append(f"**Returns**: `{func.return_type}`\n")
                if func.docstring:
                    md.append(f"{func.docstring}\n")
                md.append(f"**Defined at line**: {func.line_number}\n")
        else:
            md.append("*No functions found.*\n")
        md.append("---\n")
        
        md.append("## Classes\n")
        if analysis.classes:
            for cls in analysis.classes:
                md.append(f"### `{cls.name}`")
                if cls.base_classes:
                    md.append(f"**Inherits from**: {', '.join(cls.base_classes)}\n")
                if cls.docstring:
                    md.append(f"{cls.docstring}\n")
                md.append(f"**Methods**: {', '.join(cls.methods)}")
                md.append(f"**Attributes**: {', '.join(cls.attributes)}")
                md.append(f"**Defined at line**: {cls.line_number}\n")
        else:
            md.append("*No classes found.*\n")
        md.append("---\n")
        
        md.append("## Imports\n")
        if analysis.imports:
            for imp in analysis.imports:
                md.append(f"- `{imp.module}`: {', '.join(imp.names)}")
        else:
            md.append("*No imports found.*\n")
        md.append("\n---\n")
        
        md.append("## Diagrams\n")
        for diagram_type, diagram_code in analysis.diagrams.items():
            md.append(f"### {diagram_type.title()} Diagram\n")
            md.append("```mermaid")
            md.append(diagram_code)
            md.append("```\n")
        md.append("---\n")
        
        md.append("## Errors and Warnings\n")
        if analysis.errors:
            for error in analysis.errors:
                md.append(f"### {error.severity}: {error.category}")
                md.append(f"{error.message}")
                if error.line_number:
                    md.append(f"*Line {error.line_number}*\n")
        else:
            md.append("*No errors or warnings detected.*\n")
        
        md.append("\n---\n")
        md.append("## Original Code\n")
        md.append("```python")
        md.append(code)
        md.append("```")
        
        return "\n".join(md)