# ==========================================
# BACKEND - backend/app/storage/markdown_generator.py
# ==========================================
from ..models.schemas import CodeAnalysisResponse
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

class MarkdownGenerator:
    def generate(self, analysis: CodeAnalysisResponse, filename: str, code: str) -> str:
        """Generate comprehensive Markdown documentation"""
        logger.info(f"Generating Markdown for {filename}")
        md = []
        
        md.append(f"# Code Analysis Report: {filename}\n")
        md.append(f"*Generated by Python Code Explainer*\n")
        md.append("---\n")
        
        # Table of Contents
        md.append("## 📑 Table of Contents\n")
        md.append("1. [Overview](#overview)")
        md.append("2. [Imports](#imports)")
        md.append("3. [Variables](#variables)")
        md.append("4. [Functions](#functions)")
        md.append("5. [Classes](#classes)")
        md.append("6. [Diagrams](#diagrams)")
        md.append("7. [Suggestions](#suggestions)")
        md.append("8. [Errors & Warnings](#errors-and-warnings)")
        md.append("9. [Original Code](#original-code)\n")
        md.append("---\n")
        
        # Overview
        md.append("## 📋 Overview\n")
        md.append(analysis.detailed_overview)
        md.append("\n### Key Statistics\n")
        md.append(f"- **Variables:** {len(analysis.variables)}")
        md.append(f"- **Functions:** {len(analysis.functions)}")
        md.append(f"- **Classes:** {len(analysis.classes)}")
        md.append(f"- **Imports:** {len(analysis.imports)}")
        md.append(f"- **Issues Found:** {len(analysis.errors)}\n")
        md.append("---\n")
        
        # Imports
        md.append("## 📦 Imports\n")
        if analysis.imports:
            for imp in analysis.imports:
                md.append(f"### `{imp.module}`")
                md.append(f"**Imported:** {', '.join(imp.names)}")
                md.append(f"**Line:** {imp.line_number}")
                if imp.purpose:
                    md.append(f"\n**Purpose:** {imp.purpose}\n")
        else:
            md.append("*No imports found.*\n")
        md.append("---\n")
        
        # Variables
        md.append("## 📊 Variables\n")
        if analysis.variables:
            for var in analysis.variables:
                md.append(f"### `{var.name}` ({var.type})")
                md.append(f"- **Scope:** {var.scope}")
                md.append(f"- **Defined at line:** {var.line_number}")
                if var.occurrences:
                    md.append(f"- **Used at lines:** {', '.join(map(str, sorted(set(var.occurrences))))}\n")
        else:
            md.append("*No significant variables found.*\n")
        md.append("---\n")
        
        # Functions
        md.append("## ⚙️ Functions\n")
        if analysis.functions:
            for func in analysis.functions:
                md.append(f"### `{func.name}({', '.join(func.parameters)})`")
                if func.return_type:
                    md.append(f"**Returns:** `{func.return_type}`\n")
                md.append(f"**Defined at line:** {func.line_number}")
                
                if func.occurrences:
                    md.append(f"**Called at lines:** {', '.join(map(str, sorted(set(func.occurrences))))}")
                
                if func.variables_used:
                    md.append(f"\n**Variables used:** {', '.join(func.variables_used)}")
                
                if func.docstring:
                    md.append(f"\n**Documentation:**\n```\n{func.docstring}\n```")
                
                if func.logic_explanation:
                    md.append(f"\n**Logic Explanation:**\n{func.logic_explanation}\n")
        else:
            md.append("*No functions found.*\n")
        md.append("---\n")
        
        # Classes
        md.append("## 🏗️ Classes\n")
        if analysis.classes:
            for cls in analysis.classes:
                md.append(f"### `{cls.name}`")
                if cls.base_classes:
                    md.append(f"**Inherits from:** {', '.join(cls.base_classes)}\n")
                
                md.append(f"**Defined at line:** {cls.line_number}")
                md.append(f"**Methods:** {', '.join(cls.methods) if cls.methods else 'None'}")
                md.append(f"**Attributes:** {', '.join(cls.attributes) if cls.attributes else 'None'}")
                
                if cls.docstring:
                    md.append(f"\n**Documentation:**\n```\n{cls.docstring}\n```")
                
                if cls.detailed_explanation:
                    md.append(f"\n**Detailed Explanation:**\n{cls.detailed_explanation}\n")
        else:
            md.append("*No classes found.*\n")
        md.append("---\n")
        
        # Diagrams
        md.append("## 📈 Diagrams\n")
        for diagram_type, diagram_code in analysis.diagrams.items():
            md.append(f"### {diagram_type.title()} Diagram\n")
            md.append("```mermaid")
            md.append(diagram_code)
            md.append("```\n")
        md.append("---\n")
        
        # Suggestions
        md.append("## 💡 Improvement Suggestions\n")
        if analysis.suggestions:
            for idx, suggestion in enumerate(analysis.suggestions, 1):
                md.append(f"### {idx}. {suggestion.title}")
                md.append(f"**Category:** {suggestion.category} | **Priority:** {suggestion.priority}\n")
                md.append(suggestion.description)
                if suggestion.code_example:
                    md.append(f"\n```python\n{suggestion.code_example}\n```")
                md.append("")
        else:
            md.append("*No suggestions available.*\n")
        md.append("---\n")
        
        # Errors
        md.append("## ⚠️ Errors and Warnings\n")
        if analysis.errors:
            for error in analysis.errors:
                md.append(f"### {error.severity}: {error.category}")
                md.append(f"{error.message}")
                if error.line_number:
                    md.append(f"*Line {error.line_number}*\n")
        else:
            md.append("✅ *No errors or warnings detected.*\n")
        md.append("---\n")
        
        # Original Code
        md.append("## 💻 Original Code\n")
        md.append("```python")
        md.append(code)
        md.append("```")
        
        logger.info("Markdown generation complete")
        return "\n".join(md)
    
    def generate_formal_report(self, analysis: CodeAnalysisResponse, filename: str) -> str:
        """Generate formal PDF-ready report"""
        logger.info("Generating formal report")
        md = []
        
        md.append(f"# Technical Analysis Report\n")
        md.append(f"## {filename}\n")
        md.append(f"*Automated Code Analysis System*\n")
        md.append("---\n")
        
        # Executive Summary
        md.append("## Executive Summary\n")
        md.append(analysis.detailed_overview)
        md.append("\n---\n")
        
        # Code Structure
        md.append("## Code Structure Analysis\n")
        md.append(f"- **Total Functions:** {len(analysis.functions)}")
        md.append(f"- **Total Classes:** {len(analysis.classes)}")
        md.append(f"- **External Dependencies:** {len(analysis.imports)}")
        md.append(f"- **Code Quality Issues:** {len(analysis.errors)}\n")
        md.append("---\n")
        
        # Functions Detail
        md.append("## Function Analysis\n")
        for func in analysis.functions:
            md.append(f"### {func.name}\n")
            md.append(f"**Signature:** `{func.name}({', '.join(func.parameters)})`")
            if func.return_type:
                md.append(f" → `{func.return_type}`")
            md.append(f"\n\n{func.logic_explanation}\n")
        md.append("---\n")
        
        # Classes Detail
        md.append("## Class Analysis\n")
        for cls in analysis.classes:
            md.append(f"### {cls.name}\n")
            md.append(cls.detailed_explanation)
            md.append("")
        md.append("---\n")
        
        # Visual Diagrams
        md.append("## Architecture Diagrams\n")
        for diagram_type, diagram_code in analysis.diagrams.items():
            md.append(f"### {diagram_type.title()}\n")
            md.append("```mermaid")
            md.append(diagram_code)
            md.append("```\n")
        md.append("---\n")
        
        # Dependencies
        md.append("## Dependencies\n")
        for imp in analysis.imports:
            md.append(f"**{imp.module}:** {imp.purpose}\n")
        md.append("---\n")
        
        # Recommendations
        md.append("## Recommendations\n")
        high_priority = [s for s in analysis.suggestions if s.priority == "High"]
        medium_priority = [s for s in analysis.suggestions if s.priority == "Medium"]
        
        if high_priority:
            md.append("### High Priority\n")
            for s in high_priority:
                md.append(f"- **{s.title}:** {s.description}\n")
        
        if medium_priority:
            md.append("### Medium Priority\n")
            for s in medium_priority:
                md.append(f"- **{s.title}:** {s.description}\n")
        
        logger.info("Formal report generation complete")
        return "\n".join(md)


# ==========================================
# BACKEND - backend/app/storage/pdf_generator.py
# ==========================================
from markdown import markdown
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

class PDFGenerator:
    def generate(self, markdown_content: str) -> str:
        """Convert Markdown to styled HTML"""
        logger.info("Generating HTML from Markdown")
        html_content = markdown(
            markdown_content, 
            extensions=['fenced_code', 'tables', 'toc']
        )
        
        full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Code Analysis Report</title>
    <style>
        @media print {{ 
            body {{ margin: 2cm; }}
            .no-print {{ display: none; }}
        }}
        body {{
            font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
            background-color: #1e1e1e;
            color: #d4d4d4;
            line-height: 1.8;
            padding: 40px;
            max-width: 1200px;
            margin: 0 auto;
        }}
        h1 {{
            color: #569cd6;
            font-size: 2.5em;
            border-bottom: 3px solid #404040;
            padding-bottom: 0.5em;
            margin-top: 0;
        }}
        h2 {{
            color: #4ec9b0;
            font-size: 2em;
            border-bottom: 2px solid #404040;
            padding-bottom: 0.3em;
            margin-top: 2em;
        }}
        h3 {{
            color: #dcdcaa;
            font-size: 1.5em;
            margin-top: 1.5em;
        }}
        code {{
            background-color: #2d2d2d;
            color: #ce9178;
            padding: 3px 8px;
            border-radius: 4px;
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            font-size: 0.9em;
        }}
        pre {{
            background-color: #2d2d2d;
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            border-left: 5px solid #569cd6;
            margin: 1.5em 0;
        }}
        pre code {{
            background-color: transparent;
            padding: 0;
            color: #d4d4d4;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 1.5em 0;
        }}
        th, td {{
            border: 1px solid #404040;
            padding: 12px 15px;
            text-align: left;
        }}
        th {{
            background-color: #2d2d2d;
            font-weight: bold;
            color: #569cd6;
        }}
        tr:nth-child(even) {{
            background-color: #252525;
        }}
        hr {{
            border: none;
            border-top: 2px solid #404040;
            margin: 3em 0;
        }}
        a {{
            color: #4ec9b0;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        ul, ol {{
            line-height: 2;
        }}
        blockquote {{
            border-left: 5px solid #569cd6;
            padding-left: 1.5em;
            margin-left: 0;
            color: #9cdcfe;
            font-style: italic;
        }}
    </style>
</head>
<body>
    {html_content}
    <footer style="margin-top: 4em; padding-top: 2em; border-top: 1px solid #404040; text-align: center; color: #808080;">
        <p>Generated by Python Code Explainer | Automated Analysis System</p>
    </footer>
</body>
</html>
"""
        logger.info("HTML generation complete")
        return full_html


# ==========================================
# BACKEND - backend/app/storage/file_storage.py
# ==========================================
import os
import uuid
from pathlib import Path
from ..config import get_settings
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

class FileStorage:
    def __init__(self):
        logger.info("Initializing FileStorage")
        self.settings = get_settings()
        self.output_dir = Path(self.settings.OUTPUT_DIR)
        self.output_dir.mkdir(exist_ok=True)
        (self.output_dir / "markdown").mkdir(exist_ok=True)
        (self.output_dir / "pdf").mkdir(exist_ok=True)
        logger.debug(f"Output directory: {self.output_dir}")
    
    def save_markdown(self, content: str, filename: str) -> tuple[str, str]:
        """Save Markdown file and return (file_id, filepath)"""
        file_id = str(uuid.uuid4())
        filepath = self.output_dir / "markdown" / f"{file_id}_{filename}.md"
        
        logger.info(f"Saving Markdown: {filepath}")
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.debug(f"Markdown saved successfully. Size: {len(content)} bytes")
        return file_id, str(filepath)
    
    def save_pdf(self, content: str, filename: str, file_id: str) -> str:
        """Save HTML file and return filepath"""
        filepath = self.output_dir / "pdf" / f"{file_id}_{filename}.html"
        
        logger.info(f"Saving HTML: {filepath}")
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        
        logger.debug(f"HTML saved successfully. Size: {len(content)} bytes")
        return str(filepath)
    
    def get_markdown_path(self, file_id: str) -> str:
        """Get markdown file path by ID"""
        logger.debug(f"Looking for markdown with ID: {file_id}")
        for file in (self.output_dir / "markdown").glob(f"{file_id}_*"):
            logger.debug(f"Found: {file}")
            return str(file)
        logger.warning(f"Markdown not found for ID: {file_id}")
        return ""
    
    def get_pdf_path(self, file_id: str) -> str:
        """Get PDF/HTML file path by ID"""
        logger.debug(f"Looking for HTML with ID: {file_id}")
        for file in (self.output_dir / "pdf").glob(f"{file_id}_*"):
            logger.debug(f"Found: {file}")
            return str(file)
        logger.warning(f"HTML not found for ID: {file_id}")
        return ""