from markdown import markdown
from ..models.schemas import CodeAnalysisResponse
from ..utils.logger import setup_logger

logger = setup_logger(__name__)

class PDFGenerator:
    def generate_formal_report(self, analysis: CodeAnalysisResponse, filename: str, code: str) -> str:
        """Generate comprehensive formal PDF report in HTML format"""
        logger.info("Generating formal PDF report")
        
        # Build comprehensive report content
        report_sections = []
        
        # Title Page
        report_sections.append(f"""
# Technical Code Analysis Report
## {filename}

---

**Generated By:** Python Code Explainer System  
**Analysis Date:** {self._get_current_date()}  
**File Analyzed:** {filename}  
**Total Lines:** {len(code.split(chr(10)))}

---
""")
        
        # Executive Summary
        report_sections.append(f"""
## Executive Summary

{analysis.detailed_overview}

### Code Metrics

| Metric | Count |
|--------|-------|
| Functions | {len(analysis.functions)} |
| Classes | {len(analysis.classes)} |
| Variables | {len(analysis.variables)} |
| Imports | {len(analysis.imports)} |
| Issues Detected | {len(analysis.errors)} |

---
""")
        
        # Table of Contents
        report_sections.append("""
## Table of Contents

1. [Executive Summary](#executive-summary)
2. [Architecture Overview](#architecture-overview)
3. [Dependencies](#dependencies)
4. [Functions Analysis](#functions-analysis)
5. [Classes Analysis](#classes-analysis)
6. [Variables Reference](#variables-reference)
7. [Code Quality Assessment](#code-quality-assessment)
8. [Improvement Recommendations](#improvement-recommendations)
9. [Architecture Diagrams](#architecture-diagrams)
10. [Original Source Code](#original-source-code)

---
""")
        
        # Architecture Overview
        report_sections.append(f"""
## Architecture Overview

{analysis.overview}

### Key Components

This codebase is structured with **{len(analysis.functions)} function(s)** and **{len(analysis.classes)} class(es)**, utilizing **{len(analysis.imports)} external dependencies**. The architecture follows {"object-oriented" if analysis.classes else "procedural"} programming paradigms.

---
""")
        
        # Dependencies Section
        report_sections.append("## Dependencies\n\n")
        if analysis.imports:
            for imp in analysis.imports:
                report_sections.append(f"### {imp.module}\n")
                report_sections.append(f"**Imported Items:** {', '.join(imp.names)}\n\n")
                report_sections.append(f"**Purpose:** {imp.purpose}\n\n")
                report_sections.append(f"**Line Number:** {imp.line_number}\n\n")
        else:
            report_sections.append("*No external dependencies detected.*\n\n")
        report_sections.append("---\n\n")
        
        # Functions Analysis
        report_sections.append("## Functions Analysis\n\n")
        if analysis.functions:
            for idx, func in enumerate(analysis.functions, 1):
                params = ', '.join(func.parameters)
                report_sections.append(f"### {idx}. `{func.name}({params})`\n\n")
                
                if func.return_type:
                    report_sections.append(f"**Return Type:** `{func.return_type}`\n\n")
                
                report_sections.append(f"**Defined at Line:** {func.line_number}\n\n")
                
                if func.occurrences:
                    report_sections.append(f"**Called at Lines:** {', '.join(map(str, sorted(set(func.occurrences))))}\n\n")
                    report_sections.append(f"**Usage Frequency:** {len(set(func.occurrences))} times\n\n")
                
                if func.docstring:
                    report_sections.append(f"**Documentation:**\n```\n{func.docstring}\n```\n\n")
                
                if func.variables_used:
                    report_sections.append(f"**Variables Used:** {', '.join(func.variables_used)}\n\n")
                
                if func.logic_explanation:
                    report_sections.append(f"**Logic Explanation:**\n\n{func.logic_explanation}\n\n")
                
                report_sections.append("---\n\n")
        else:
            report_sections.append("*No functions defined in this file.*\n\n---\n\n")
        
        # Classes Analysis
        report_sections.append("## Classes Analysis\n\n")
        if analysis.classes:
            for idx, cls in enumerate(analysis.classes, 1):
                report_sections.append(f"### {idx}. Class: `{cls.name}`\n\n")
                
                if cls.base_classes:
                    report_sections.append(f"**Inherits From:** {', '.join(cls.base_classes)}\n\n")
                
                report_sections.append(f"**Defined at Line:** {cls.line_number}\n\n")
                
                report_sections.append(f"**Methods ({len(cls.methods)}):** {', '.join(cls.methods) if cls.methods else 'None'}\n\n")
                report_sections.append(f"**Attributes ({len(cls.attributes)}):** {', '.join(cls.attributes) if cls.attributes else 'None'}\n\n")
                
                if cls.docstring:
                    report_sections.append(f"**Documentation:**\n```\n{cls.docstring}\n```\n\n")
                
                if cls.detailed_explanation:
                    report_sections.append(f"**Overview:**\n\n{cls.detailed_explanation}\n\n")
                
                # Method Details
                if cls.method_explanations:
                    report_sections.append("**Method Details:**\n\n")
                    for method_name, explanation in cls.method_explanations.items():
                        report_sections.append(f"#### `{method_name}()`\n\n")
                        report_sections.append(f"{explanation}\n\n")
                
                report_sections.append("---\n\n")
        else:
            report_sections.append("*No classes defined in this file.*\n\n---\n\n")
        
        # Variables Reference
        report_sections.append("## Variables Reference\n\n")
        if analysis.variables:
            # Group by scope
            global_vars = [v for v in analysis.variables if v.scope == 'global']
            function_vars = [v for v in analysis.variables if v.scope.startswith('function:')]
            
            if global_vars:
                report_sections.append("### Global Variables\n\n")
                report_sections.append("| Name | Type | Line | Occurrences |\n")
                report_sections.append("|------|------|------|-------------|\n")
                for var in global_vars:
                    occurrences = ', '.join(map(str, sorted(set(var.occurrences)))) if var.occurrences else 'N/A'
                    report_sections.append(f"| `{var.name}` | {var.type} | {var.line_number} | {occurrences} |\n")
                report_sections.append("\n")
            
            if function_vars:
                report_sections.append("### Function-Scoped Variables\n\n")
                by_function = {}
                for var in function_vars:
                    func_name = var.scope.split(':')[1]
                    if func_name not in by_function:
                        by_function[func_name] = []
                    by_function[func_name].append(var)
                
                for func_name, vars_list in by_function.items():
                    report_sections.append(f"#### Function: `{func_name}`\n\n")
                    report_sections.append("| Name | Type | Line | Uses |\n")
                    report_sections.append("|------|------|------|------|\n")
                    for var in vars_list:
                        uses = len(set(var.occurrences)) if var.occurrences else 0
                        report_sections.append(f"| `{var.name}` | {var.type} | {var.line_number} | {uses} |\n")
                    report_sections.append("\n")
        else:
            report_sections.append("*No significant variables detected.*\n\n")
        report_sections.append("---\n\n")
        
        # Code Quality Assessment
        report_sections.append("## Code Quality Assessment\n\n")
        if analysis.errors:
            critical = [e for e in analysis.errors if e.severity == 'Critical']
            warnings = [e for e in analysis.errors if e.severity == 'Warning']
            info = [e for e in analysis.errors if e.severity == 'Info']
            
            report_sections.append(f"**Total Issues:** {len(analysis.errors)}\n\n")
            report_sections.append(f"- Critical: {len(critical)}\n")
            report_sections.append(f"- Warnings: {len(warnings)}\n")
            report_sections.append(f"- Info: {len(info)}\n\n")
            
            if critical:
                report_sections.append("### Critical Issues\n\n")
                for error in critical:
                    report_sections.append(f"**{error.category}**\n\n")
                    report_sections.append(f"{error.message}\n\n")
                    if error.line_number:
                        report_sections.append(f"*Line {error.line_number}*\n\n")
            
            if warnings:
                report_sections.append("### Warnings\n\n")
                for error in warnings:
                    report_sections.append(f"**{error.category}**\n\n")
                    report_sections.append(f"{error.message}\n\n")
                    if error.line_number:
                        report_sections.append(f"*Line {error.line_number}*\n\n")
        else:
            report_sections.append("✅ **No issues detected.** Code quality is excellent.\n\n")
        report_sections.append("---\n\n")
        
        # Improvement Recommendations
        report_sections.append("## Improvement Recommendations\n\n")
        if analysis.suggestions:
            # Group by priority
            high = [s for s in analysis.suggestions if s.priority == 'High']
            medium = [s for s in analysis.suggestions if s.priority == 'Medium']
            low = [s for s in analysis.suggestions if s.priority == 'Low']
            
            if high:
                report_sections.append("### High Priority\n\n")
                for idx, s in enumerate(high, 1):
                    report_sections.append(f"#### {idx}. {s.title}\n\n")
                    report_sections.append(f"**Category:** {s.category}\n\n")
                    report_sections.append(f"{s.description}\n\n")
                    if s.code_example:
                        report_sections.append(f"**Example:**\n```python\n{s.code_example}\n```\n\n")
            
            if medium:
                report_sections.append("### Medium Priority\n\n")
                for idx, s in enumerate(medium, 1):
                    report_sections.append(f"#### {idx}. {s.title}\n\n")
                    report_sections.append(f"**Category:** {s.category}\n\n")
                    report_sections.append(f"{s.description}\n\n")
            
            if low:
                report_sections.append("### Low Priority\n\n")
                for idx, s in enumerate(low, 1):
                    report_sections.append(f"**{idx}. {s.title}** ({s.category}): {s.description}\n\n")
        else:
            report_sections.append("*No specific recommendations at this time.*\n\n")
        report_sections.append("---\n\n")
        
        # Architecture Diagrams
        report_sections.append("## Architecture Diagrams\n\n")
        if analysis.diagrams:
            for diagram_type, diagram_code in analysis.diagrams.items():
                report_sections.append(f"### {diagram_type.title()} Diagram\n\n")
                report_sections.append("```mermaid\n")
                report_sections.append(diagram_code)
                report_sections.append("\n```\n\n")
        report_sections.append("---\n\n")
        
        # Original Source Code
        report_sections.append("## Original Source Code\n\n")
        report_sections.append("```python\n")
        report_sections.append(code)
        report_sections.append("\n```\n\n")
        
        # Combine all sections
        full_markdown = ''.join(report_sections)
        
        # Convert to HTML
        html_content = markdown(full_markdown, extensions=['fenced_code', 'tables', 'toc'])
        
        # Wrap in professional HTML template
        final_html = self._wrap_in_template(html_content, filename)
        
        logger.info("Formal report generation complete")
        return final_html
    
    def _wrap_in_template(self, content: str, filename: str) -> str:
        """Wrap content in professional HTML template"""
        return f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Technical Analysis Report - {filename}</title>
    <style>
        @media print {{
            body {{ margin: 1.5cm; }}
            .page-break {{ page-break-before: always; }}
        }}
        
        * {{
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }}
        
        body {{
            font-family: 'Segoe UI', 'Arial', sans-serif;
            line-height: 1.8;
            color: #2c3e50;
            background: #ffffff;
            padding: 40px;
            max-width: 1200px;
            margin: 0 auto;
        }}
        
        h1 {{
            color: #1a202c;
            font-size: 2.5em;
            margin: 1.5em 0 0.5em 0;
            border-bottom: 4px solid #3498db;
            padding-bottom: 0.3em;
        }}
        
        h2 {{
            color: #2c5282;
            font-size: 2em;
            margin: 2em 0 1em 0;
            border-bottom: 2px solid #4299e1;
            padding-bottom: 0.3em;
        }}
        
        h3 {{
            color: #2d3748;
            font-size: 1.5em;
            margin: 1.5em 0 0.8em 0;
        }}
        
        h4 {{
            color: #4a5568;
            font-size: 1.2em;
            margin: 1em 0 0.5em 0;
        }}
        
        p {{
            margin: 1em 0;
            text-align: justify;
        }}
        
        code {{
            background-color: #f7fafc;
            color: #c7254e;
            padding: 3px 6px;
            border-radius: 3px;
            font-family: 'Consolas', 'Monaco', 'Courier New', monospace;
            font-size: 0.9em;
            border: 1px solid #e2e8f0;
        }}
        
        pre {{
            background-color: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            margin: 1.5em 0;
            border-left: 5px solid #3498db;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        
        pre code {{
            background-color: transparent;
            color: #e2e8f0;
            padding: 0;
            border: none;
            font-size: 0.95em;
        }}
        
        table {{
            width: 100%;
            border-collapse: collapse;
            margin: 1.5em 0;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        
        th {{
            background-color: #3498db;
            color: white;
            padding: 12px 15px;
            text-align: left;
            font-weight: 600;
        }}
        
        td {{
            padding: 12px 15px;
            border-bottom: 1px solid #e2e8f0;
        }}
        
        tr:nth-child(even) {{
            background-color: #f7fafc;
        }}
        
        tr:hover {{
            background-color: #edf2f7;
        }}
        
        hr {{
            border: none;
            border-top: 2px solid #cbd5e0;
            margin: 3em 0;
        }}
        
        blockquote {{
            border-left: 5px solid #3498db;
            padding-left: 1.5em;
            margin: 1.5em 0;
            color: #4a5568;
            font-style: italic;
        }}
        
        ul, ol {{
            margin: 1em 0 1em 2em;
        }}
        
        li {{
            margin: 0.5em 0;
        }}
        
        .header {{
            text-align: center;
            padding: 40px 0;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            border-radius: 10px;
            margin-bottom: 40px;
        }}
        
        .header h1 {{
            color: white;
            border: none;
            margin: 0;
        }}
        
        .header p {{
            margin: 10px 0;
            font-size: 1.1em;
        }}
        
        .footer {{
            margin-top: 60px;
            padding-top: 30px;
            border-top: 2px solid #cbd5e0;
            text-align: center;
            color: #718096;
            font-size: 0.9em;
        }}
        
        .metric-badge {{
            display: inline-block;
            background: #edf2f7;
            padding: 8px 16px;
            border-radius: 20px;
            margin: 5px;
            font-weight: 600;
            color: #2d3748;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>📊 Technical Code Analysis Report</h1>
        <p><strong>{filename}</strong></p>
        <p>Generated by Python Code Explainer System</p>
    </div>
    
    {content}
    
    <div class="footer">
        <p>This report was automatically generated by Python Code Explainer</p>
        <p>For questions or support, contact your development team</p>
    </div>
</body>
</html>
"""
    
    def _get_current_date(self) -> str:
        """Get current date formatted"""
        from datetime import datetime
        return datetime.now().strftime("%B %d, %Y")